feat: format with docker

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,10 +1,17 @@
 #!/bin/bash
+echo "Running PHP CS Fixer using Docker with PHP 8.1..."
 
-echo "Running PHP CS Fixer..."
-./vendor/bin/php-cs-fixer fix .
+docker run --rm \
+  -v "$(pwd):/app" \
+  -w /app \
+  php:8.1-cli \
+  ./vendor/bin/php-cs-fixer fix .
 
-# Add the fixed files to the commit
+if [ $? -ne 0 ]; then
+  echo "PHP CS Fixer failed!"
+  exit 1
+fi
+
 git add -u
 
-# Continue with the commit
 exit 0
